general:
  project_name: sweep_test
  uv_env: pyproject.toml
  entity: spatial_vi
  modules: stack eth_proxy

slurm:
  time: "00:10:00"
  mem_per_cpu: "4G"
  job_name: sweep_uv
  output: slurm_logs/wandb_uv_%A_%a.out
  array: "0"

wandb:
  program: ../simple/train.py
  method: grid
  name: sweep_uv

  metric:
    goal: maximize
    name: val_acc
  parameters:
    batch_size:
      value: 32
    lr:
      value: 0.01
    epochs:
      values: [2, 3]
